name: Security Scan

on:
  schedule:
    - cron: "0 12 * * 1" # 12pm UTC every Monday
  workflow_dispatch:

jobs:
  code_scan:
    name: SAST scan
    uses: Basis-Theory/security-workflows/.github/workflows/code-scan.yml@master
    secrets: inherit
    with:
      app-name: android-elements

  dependency_scan:
    name: SCA scan
    uses: Basis-Theory/security-workflows/.github/workflows/dependency-scan.yml@master
    secrets: inherit
    with:
      app-name: android-elements